/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 16:30:24 GMT 2024
 */

package com.iluwatar.ambassador;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.ambassador.RemoteService;
import com.iluwatar.ambassador.util.RandomProvider;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.jupiter.api.extension.RegisterExtension;

 
import org.junit.jupiter.api.Disabled;
public class RemoteService_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      RandomProvider randomProvider0 = mock(RandomProvider.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(randomProvider0).random();
      RemoteService remoteService0 = new RemoteService(randomProvider0);
      long long0 = remoteService0.doRemoteFunction(0);
      assertEquals(0L, long0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  @Disabled
    public void test1()  throws Throwable  {
      RemoteService remoteService0 = RemoteService.getRemoteService();
      assertNotNull(remoteService0);
      
      long long0 = remoteService0.doRemoteFunction((-1742));
      assertEquals((-17420L), long0);
      
      long long1 = remoteService0.doRemoteFunction(375);
      assertEquals((-1L), long1);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      RemoteService remoteService0 = new RemoteService((RandomProvider) null);
      // Undeclared exception!
      try { 
        remoteService0.doRemoteFunction(2265);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.ambassador.RemoteService", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      RandomProvider randomProvider0 = mock(RandomProvider.class, new ViolatedAssumptionAnswer());
      doReturn((-1050.8703)).when(randomProvider0).random();
      RemoteService remoteService0 = new RemoteService(randomProvider0);
      // Undeclared exception!
      try { 
        remoteService0.doRemoteFunction((-121));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         verifyException("java.lang.Thread", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      RemoteService remoteService0 = RemoteService.getRemoteService();
      RemoteService remoteService1 = RemoteService.getRemoteService();
      assertSame(remoteService1, remoteService0);
  }
}
